export const M4_DEFAULT_REALM_TREASURY = 1000
export const M4_DEFAULT_REALM_FOOD_STORES = 2000
export const M4_DEFAULT_TAX_RATE = 10
export const M4_MAX_TAX_RATE = 50
export const M4_DEFAULT_SITE_POPULATION = 10000
export const M4_HOUSEHOLD_DIVISOR = 5
export const M4_BASE_FOOD_PRODUCTION_PER_HOUSEHOLD = 2
export const M4_FOOD_CONSUMPTION_PER_HOUSEHOLD = 3
export const M4_BASE_TAX_PER_HOUSEHOLD = 1
export const M4_TAX_RATE_DIVISOR = 100
export const M4_POPULATION_GROWTH_BASIS_POINTS = 100
export const M4_BASIS_POINTS_DIVISOR = 10000
export const M4_EDICT_TAX_RELIEF_MODIFIER = -5
export const M4_EDICT_GRAIN_RESERVE_MODIFIER = 10
export const M4_EDICT_TAX_RELIEF_TAX_INCOME_BASIS_POINTS = -2500
export const M4_EDICT_TAX_RELIEF_POPULATION_GROWTH_BASIS_POINTS = 5
export const M4_EDICT_GRAIN_RESERVE_FOOD_PRODUCTION_BASIS_POINTS = 1000
export const M4_EDICT_GRAIN_RESERVE_TREASURY_COST = 10
/** @deprecated since M5 — replaced by attrs.zheng-based calculation (M5_GOVERNOR_TAX_BONUS_PER_ZHENG × zheng) */
export const M4_GOVERNOR_TAX_MODIFIER = 5
/** @deprecated since M5 — replaced by attrs.zheng-based calculation (M5_GOVERNOR_FOOD_BONUS_PER_ZHENG × zheng) */
export const M4_GOVERNOR_FOOD_MODIFIER = 5
export const M4_TRIBUTE_AMOUNT_MIN = 0
export const M4_TRIBUTE_AMOUNT_MAX = 5000
export const M4_INDEMNITY_AMOUNT_MAX = 100000
export const M4_MONTHS_PER_SEASON = 3
export const M4_MONTHS_PER_YEAR = 12

export const AI_SIEGE_MIN_ADVANTAGE_RATIO = 1.2
export const AI_SIEGE_BASE_SCORE = 60
export const AI_SIEGE_SUPPLY_SCORE = 30
export const AI_SIEGE_ADVANTAGE_SCORE_CAP = 50

export const AI_CUT_SUPPLY_MIN_MANPOWER = 1500
export const AI_CUT_SUPPLY_MAX_ENCIRCLEMENT = 0.5
export const AI_CUT_SUPPLY_BASE_SCORE = 40
export const AI_CUT_SUPPLY_ENEMY_CONTROL_SCORE_SCALE = 30

export const AI_RETREAT_OUTNUMBERED_RATIO = 0.7
export const AI_RETREAT_LOW_SUPPLY_THRESHOLD = 5
export const AI_RETREAT_BASE_SCORE = 40
export const AI_RETREAT_LOW_SUPPLY_SCORE = 30
export const AI_RETREAT_DISADVANTAGE_SCORE_CAP = 50
export const AI_RETREAT_DISADVANTAGE_SCORE_SCALE = 50

export const DIPLOMACY_ATTITUDE_MIN = -100
export const DIPLOMACY_ATTITUDE_MAX = 100
export const DIPLOMACY_TRUST_MIN = 0
export const DIPLOMACY_TRUST_MAX = 100
export const DIPLOMACY_PROPOSAL_DURATION_TICKS = 9
export const DIPLOMACY_TRUCE_DURATION_TICKS = 36
export const DIPLOMACY_NON_AGGRESSION_DURATION_TICKS = 72
export const DIPLOMACY_COALITION_THREAT_THRESHOLD = 70
export const DIPLOMACY_COALITION_DISSOLVE_THREAT_THRESHOLD = 45
export const DIPLOMACY_COALITION_MIN_MEMBERS = 2
export const DIPLOMACY_COALITION_WAR_THREAT_BONUS = 20
export const DIPLOMACY_BETRAYAL_TRUST_DELTA = -30
export const DIPLOMACY_THIRD_PARTY_DECLARE_WAR_AGGRESSOR_ATTITUDE_DELTA = -12
export const DIPLOMACY_THIRD_PARTY_DECLARE_WAR_AGGRESSOR_TRUST_DELTA = -6
export const DIPLOMACY_THIRD_PARTY_DECLARE_WAR_TARGET_ATTITUDE_DELTA = 4
export const DIPLOMACY_THIRD_PARTY_DECLARE_WAR_TARGET_TRUST_DELTA = 2
export const DIPLOMACY_ACCEPTANCE_BASE = 0
export const DIPLOMACY_ACCEPTANCE_ATTITUDE_THRESHOLD = 0
export const DIPLOMACY_ACCEPTANCE_TRUST_THRESHOLD = 50
export const DIPLOMACY_ACCEPTANCE_ATTITUDE_WEIGHT = 0.5
export const DIPLOMACY_ACCEPTANCE_TRUST_WEIGHT = 0.4
export const DIPLOMACY_ACCEPTANCE_EXISTING_WAR_MODIFIER = -40
export const DIPLOMACY_ACCEPTANCE_TRUCE_MODIFIER = -80
export const DIPLOMACY_ACCEPTANCE_TREATY_CONFLICT_MODIFIER = -60
export const DIPLOMACY_ACCEPTANCE_THREAT_WEIGHT = 0.2
export const DIPLOMACY_ZHOU_INVESTITURE_ACCEPTANCE_MODIFIER = 10
export const DIPLOMACY_ZHOU_INVESTITURE_REACTION_MODIFIER = 10
export const DIPLOMACY_THREAT_SITE_POWER = 10
export const DIPLOMACY_THREAT_ARMY_MANPOWER_DIVISOR = 1000
export const DIPLOMACY_THREAT_MANPOWER_DIVISOR = 1000
export const DIPLOMACY_RELATION_DRIFT_INTERVAL_TICKS = 6
export const DIPLOMACY_RELATION_DRIFT_DELTA = 1
export const DIPLOMACY_RELATION_NEUTRAL_ATTITUDE = 0
export const DIPLOMACY_RELATION_NEUTRAL_TRUST = 50
export const DIPLOMACY_ACTION_COSTS = {
  alliance: 35,
  non_aggression: 15,
  tribute: 25,
  marriage: 20,
  envoy: 5,
  declare_war: 30,
  peace: 10,
}
